services:
  - type: web
    name: estatex-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: ENV
        value: production
      - key: API_V1_STR
        value: /api/v1
      - key: CORS_ORIGINS
        value: "*"
      - key: PYTHON_VERSION
        value: 3.11
    healthCheckPath: /api/v1/health
